### ISSUE TITLE
daemon/core: #2991 leaves `ZENOH_CONFIG_PATH_ENV` un-gated, breaking `cargo build -p dora-core` (and any isolated build) without the `zenoh` feature

### ISSUE THREAD

**Issue by phil-opp** [dora-rs/dora#2995]
> ⚠️ **This issue was created by a scheduled, automated Claude code-review check.** It was not filed by a human. Please verify the finding before acting on it. This one is directly reproducible (`cargo build -p dora-core`).

## Summary

PR #2991 (commit `137208a`, the "close ZENOH_CONFIG bypass" sub-commit) added a top-level `pub const` in `libraries/core/src/topics.rs` that references the `zenoh` crate **without** a `#[cfg(feature = "zenoh")]` gate, even though every neighboring zenoh-touching item in the file is gated. Because `zenoh` is an **optional, non-default** dependency of `dora-core`, any build of the crate that does not enable the feature now fails to compile.

## Location

`libraries/core/src/topics.rs:63`

```rust
pub const ZENOH_CONFIG_PATH_ENV: &str = zenoh::Config::DEFAULT_CONFIG_PATH_ENV;
```

`libraries/core/Cargo.toml`:

```toml
[features]
build = ["dep:git2", "dep:url"]
zenoh = ["dep:zenoh"]      # optional, NOT in any default set

[dependencies]
zenoh = { workspace = true, optional = true }
```

## Reproduction (confirmed on current `main`, HEAD `596f27b`)

```
$ cargo build -p dora-core
   Compiling dora-core v1.0.0-rc.4 (/…/libraries/core)
error[E0433]: failed to resolve: use of unresolved module or unlinked crate `zenoh`
  63 | pub const ZENOH_CONFIG_PATH_ENV: &str = zenoh::Config::DEFAULT_CONFIG_PATH_ENV;
     |                                         ^^^^^ use of unresolved module or unlinked crate `zenoh`
error: could not compile `dora-core` (lib) due to 1 previous error

$ cargo build -p dora-core --features zenoh
   Finished        # OK
```

## Blast radius

- `cargo build -p dora-core` and `cargo test -p dora-core` — both are the single-crate commands explicitly documented in `CLAUDE.md` ("Build specific package" / "Test single package") and are the fast local iteration loop the project recommends.
- Any downstream crate that depends on `dora-core` **without** enabling `zenoh`, when built in isolation. Confirmed candidates: `dora-runtime` and `dora-hub-client` both declare `dora-core = { workspace = true }` with no `zenoh` feature, so `cargo build -p dora-runtime` / `-p dora-hub-client` hit the same error in a clean, non-unified build.

## Why CI stayed green

The PR gate runs `cargo build/clippy/test --all` over the whole workspace. Feature unification means `dora-daemon`/`dora-cli`/`dora-coordinator` (which do enable `dora-core/zenoh`) turn the feature on for the shared `dora-core` build, so the const resolves. The breakage only surfaces on **per-crate** builds — precisely the fast loop that isn't in CI.

## Suggested fix

Gate the const exactly like its neighbors:

```rust
#[cfg(feature = "zenoh")]
pub const ZENOH_CONFIG_PATH_ENV: &str = zenoh::Config::DEFAULT_CONFIG_PATH_ENV;
```

The only consumers are `open_zenoh_session_with_listen` (already `#[cfg(feature = "zenoh")]`) and `binaries/daemon/src/spawn/spawner.rs::is_denied_env` in the daemon (which always enables `dora-core/zenoh`), so gating is safe. Optionally add a CI job that builds the affected crates with default features to prevent regressions of this class.
